### ISSUE TITLE
Double animation on page load

### ISSUE THREAD

**Issue by AaronWeb** [TiagoSilvaPereira/laraestimate#2]
Hi Tiago! This is my first ever GitHub issue creation!

Loving the app. I did notice a double animation on page load. I'll attach a GIF of what I've seeing.
![double-animation](https://user-images.githubusercontent.com/3227708/78203551-4d8fa580-7465-11ea-8d68-fc4cdd95bfb6.gif)

**Comment by TiagoSilvaPereira** [comment]
Hi @AaronWeb thanks for opening this issue... I'll try to debug it. Could you try on another browser too see if the issues always happen?

**Comment by AaronWeb** [comment]
It's related to LiveReload.js . When I changed my .env file to anything but "local", it doesn't happen.
Pretty low priority, if at all.

**Comment by TiagoSilvaPereira** [comment]
Hi @AaronWeb as it is not a bug, I'll close for now ok? Thanks for reporting man!
